In [39]:
from maze import *

class QPlayer():
    
    EXPLORE = 0.01
    
    N,S,E,W = 0,1,2,3
    
    def __init__(self):
        super().__init__()
        self.q_table = np.zeros([4*4,4])
        
    def run(self, environment, explore=EXPLORE):
        observation = environment.reset()
        done = False
        complete = 0
        while not done:
            state = observation[0] * 4 + observation[1]
            action = np.argmax(self.q_table[state])
            if action == 0 or np.random.random() < explore:
                action = environment.sample()
            observation, reward, done = environment.step(action)
            if done:
                self.q_table[state][action] = reward
                return reward
            else:
                future_state = observation[0] * 4 + observation[1]
                self.q_table[state][action] += reward + np.amax(self.q_table[future_state])

In [40]:
q = QPlayer()
e = Maze()
complete = 0
for n in range(100000):
    complete += 1 if q.run(e) > 0 else 0
    if np.sum(q.q_table) > 100:
        print(q.q_table)
        break

[[-1.  0. 21. -1.]
 [-1. -1. 35.  0.]
 [-1. 35. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 0. -1. 21. -1.]
 [-1.  7. -1.  0.]
 [ 0. -1.  0. -1.]
 [-1. -1. -1.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  1. -1. -1.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [41]:
q.run(e, explore=0.0)
print(e)

         ...  ...  ...  +++ 
enter->  (1)  (2)  (3)  +++ 
         ...  ...  ...  +++ 

         ...  +++  ...  ... 
         ...  +++  (4)  (5) 
         ...  +++  ...  ... 

         ...  ...  +++  ... 
         ...  ...  +++  (6) 
         ...  ...  +++  ... 

         +++  +++  ...  ... 
         +++  +++  ...  (7)  <-exit
         +++  +++  ...  ... 



In [42]:
q.run(e, explore=1.0)
print(e)

         ...  ...  ...  +++ 
enter->  (1)  ...  ...  +++ 
         ...  ...  ...  +++ 

         ...  +++  ...  ... 
         ...  +++  ...  ... 
         ...  +++  ...  ... 

         ...  ...  +++  ... 
         ...  ...  +++  ... 
         ...  ...  +++  ... 

         +++  +++  ...  ... 
         +++  +++  ...  ...  <-exit
         +++  +++  ...  ... 

